Task 1.a

In [1]:
import numpy as np

def d_e(v_0, v_mean):
    return (v_0 - v_mean).T@(v_0 - v_mean)


def d_m(v_0, v_mean, S):
    return (v_0 - v_mean).T@np.linalg.inv(S)@(v_0 - v_mean)

In [2]:
v_mean = np.array([[0], [1], [1]])
v_0 = np.array([[2], [5], [3]])
S = np.array([[5, 1, 2],
              [1, 6, 1],
              [2, 1, 7]])

In [4]:
print(f"d_e = {d_e(v_0, v_mean)}")

d_e = [[24]]

In [5]:
print(f"d_m = {d_m(v_0, v_mean, S)}")

d_m = [[3.14606742]]

Task 1.b.ii

In [7]:
v_mean = np.array([[0], [1], [1]])
v_0 = np.array([[20], [5], [3]])
S = np.array([[500, 10, 20],
              [10, 6, 1],
              [20, 1, 7]])

In [8]:
print(f"d_e = {d_e(v_0, v_mean)}")

d_e = [[420]]

In [9]:
print(f"d_m = {d_m(v_0, v_mean, S)}")

d_m = [[3.14606742]]

Task 2.b

In [1]:
import sympy as sp

a, b = sp.symbols('a b')

A = sp.Matrix([
    [1, a, 0],
    [0, 1, 0],
    [0, 0, b]
])

A_inv = A.inv()
A_inv

Matrix([
[1, -a,   0],
[0,  1,   0],
[0,  0, 1/b]])

Task 3

In [2]:
import pandas as pd

df = pd.read_csv('dataFig311.csv')
df

          lnwage  educ
0       5.790019    12
1       5.952494    11
2       5.315949    12
3       5.595926    12
4       6.068915    12
...          ...   ...
329504  6.323980    16
329505  5.847161    15
329506  5.909597    12
329507  6.047781     5
329508  5.766817    19

[329509 rows x 2 columns]

In [3]:
import statsmodels.api as sm

X = df['educ']
y = df['lnwage']
X = sm.add_constant(X)
model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 lnwage   R-squared:                       0.117
Model:                            OLS   Adj. R-squared:                  0.117
Method:                 Least Squares   F-statistic:                 4.378e+04
Date:                Sun, 05 Oct 2025   Prob (F-statistic):               0.00
Time:                        15:48:20   Log-Likelihood:            -3.1935e+05
No. Observations:              329509   AIC:                         6.387e+05
Df Residuals:                  329507   BIC:                         6.387e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.9952      0.004   1118.882      0.000       4.986       5.004
educ           0.0709      0.000    209.243      0.000       0.070       0.072
==============================================================================
Omnibus:                   191064.432   Durbin-Watson:                   1.870
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          4082109.888
Skew:                          -2.377   Prob(JB):                         0.00
Kurtosis:                      19.575   Cond. No.                         53.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [11]:
df_agg = df.groupby(by='educ', as_index=False).agg(
    mean =('lnwage', 'mean'),
    cnt =('lnwage', 'size')
)

df_agg

    educ      mean     cnt
0      0  5.022035     598
1      1  5.064200     215
2      2  5.166692     606
3      3  5.173006    1089
4      4  5.264427    1345
5      5  5.330808    2003
6      6  5.403939    3874
7      7  5.470224    6177
8      8  5.572456   16118
9      9  5.646150   13183
10    10  5.685303   16530
11    11  5.731728   13674
12    12  5.844358  122934
13    13  5.917124   18257
14    14  5.962863   25681
15    15  6.007515    9973
16    16  6.231889   35747
17    17  6.229527   12063
18    18  6.268082   11655
19    19  6.211449    6307
20    20  6.310895   11480

In [12]:
X = df_agg['educ']
y = df_agg['mean']
weights = df_agg['cnt']
X = sm.add_constant(X)
model = sm.WLS(y, X, weights=weights).fit()
print(model.summary())

                            WLS Regression Results
==============================================================================
Dep. Variable:                   mean   R-squared:                       0.962
Model:                            WLS   Adj. R-squared:                  0.960
Method:                 Least Squares   F-statistic:                     485.2
Date:                Sun, 05 Oct 2025   Prob (F-statistic):           5.46e-15
Time:                        16:00:36   Log-Likelihood:                 25.228
No. Observations:                  21   AIC:                            -46.46
Df Residuals:                      19   BIC:                            -44.37
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.9952      0.042    117.790      0.000       4.906       5.084
educ           0.0709      0.003     22.028      0.000       0.064       0.078
==============================================================================
Omnibus:                       20.895   Durbin-Watson:                   1.511
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               34.903
Skew:                           1.617   Prob(JB):                     2.64e-08
Kurtosis:                       8.425   Cond. No.                         53.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.